Portfolio:Details popup window
MPDADDY/my_portfolio pull request #8
Opened 2023-07-26 12:54 UTC by MPDADDY

This branch contains a popup feature for the portfolio webpage.
Required changes have been implemented.
Done with the requested changes.

2023-07-26 14:34 UTC, shahadat3669 requested changes
Hi @MPDADDY, @Obimbo07 , 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Descriptive PR Title
✅ Descriptive PR Description


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +  },
Great job on creating the objects for each project! You have included the necessary information such as title, description, and featured image. However, as per the project requirements, each project object should also include the following attributes: technologies, link to the live version, and link to the project source code.

For example, your project object should look like this:

```javascript
const Articles = [{
    heading: "Submarine game",
    description: "description",
    image: "link_to_image.jpg",
    technologies: ["JavaScript", "Jest"],
    link: "link_to_live_version.com",
    sourceCode: "link_to_project_source_code.com"
}]
```

Please make sure to add the technologies, link, and sourceCode attributes to each project object to meet the project requirements. This will ensure that all the necessary information is available for each project, and your project will be complete and ready for review. Keep up the good work! 👍📚🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    <p>A daily selection of privately personalized reads; no accounts or sign-ups required.</p>
Well done on creating dynamic headings for each project! However, it seems that the project descriptions are not being generated dynamically as specified in the project requirements. To meet these requirements, it is necessary to also display the description for each project dynamically. Please revise your code accordingly. Thank you! 👍

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    </ul>
- [ ] Great job on implementing dynamic headings for each project! However, it appears that the project technologies are not being generated dynamically as the project requirements specify. To meet these requirements, it is essential to display the technologies for each project dynamically as well. Please review your code and make the necessary adjustments. Thank you for your effort! 👍

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                <h2>Tonic</h2>
- [ ] Hello there! It seems that the heading in the popup is not being generated dynamically, which goes against the project requirements. In order to comply with these requirements, it is necessary to display the heading dynamically for each project in the popup. Kindly review your code and make the necessary adjustments. Thank you for your hard work! 👍

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                <img src="${Articles[i].desktopImg}" alt="popup image">r
- [ ] Well done on attempting to dynamically show the images! However, I noticed that the popup image displayed when clicking the "Show Project" button is not matching the corresponding project image. Currently, the same popup image is shown for all projects, but it should dynamically display the image related to the project for which the "Show Project" button was clicked.

[Portfolio.webm](https://github.com/MPDADDY/my_portfolio/assets/55840999/387f44ab-0374-479b-8244-74765199d75d)

By updating your code, the popup image will now correctly match the corresponding project image when the "Show Project" button is clicked. Keep up the good work, and happy coding! 📷🚀👍

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                        ullam eos ducimus magni dolor facere saepe.</p>
- [ ] Hello there! It seems that the description in the popup is not being generated dynamically, which goes against the project requirements. In order to comply with these requirements, it is necessary to display the description dynamically for each project in the popup. Kindly review your code and make the necessary adjustments. Thank you for your hard work! 👍

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    </ul>
- [ ] Hello there! It seems that the technologies in the popup is not being generated dynamically, which goes against the project requirements. In order to comply with these requirements, it is necessary to display the technologies dynamically for each project in the popup. Kindly review your code and make the necessary adjustments. Thank you for your hard work! 👍

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    <button class="popup-links" type="button">See source</button>
- [ ] Great job on dynamically generating the project cards! However, currently, the buttons don't have any functionality, and they should redirect users to the proper source code or live demo links when clicked. Additionally, if a project link is not available, you can replace it with a placeholder link, but the buttons need to work correctly and redirect users accordingly.

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +        <div class="desktopPopup">
Thank you for your efforts in creating the section. However, there are some adjustments needed to match the design requirements:

1. Padding: Currently, you have set the padding to 1rem (16px) for the desktop version, but as per the design, it should be 24px. Please update your code to match the design and add the necessary padding. note: for mobile version, it should be 16px.

2. Border Radius: The design requires a border-radius of 16px, but it is currently missing. Please add the specified border-radius to match the design.

3. Gap: In the mobile version, there should be a 16px gap between the screen edge and the div. Please follow the design and add the necessary gaps to match the design.
![image](https://github.com/MPDADDY/my_portfolio/assets/55840999/4da67f1a-0431-4a23-a771-3d0d57fc6776)
By making these adjustments, your section will align with the design and create a more visually appealing and consistent user experience. Keep up the good work, and I'm confident that your attention to detail will make your project shine! 👏🌟🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                <h2>Tonic</h2>
Well done on adding the title to your section! However, there are some adjustments needed to match the design requirements:

1. Font Styles: The title font styles, such as line height and font size, do not match the design. Please carefully follow the design and update your code to match the specified font styles. note: There should be different font styles for desktop and mobile versions.

By making these adjustments, your title will align with the design and create a more cohesive and visually appealing section. Keep up the good work, and I'm confident that your attention to detail will make your project shine! 👍🌟🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                <button type='button' id= "closePopup" class="closePopup">x</button>
Great job on adding the icon! However, there is a small adjustment needed to match the design requirements:

1. Icon Size: The current icon size is larger than what is specified in the design. Please carefully follow the design and update your code to match the specified icon size.

By making this adjustment, your icon will align with the design and create a more visually consistent and professional look. Keep up the good work, and I'm sure your attention to detail will make your project even better! 👍🌟🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +            <div class="popupImg">
Well done on implementing the "popupImg" section! However, there is a small adjustment needed to match the design requirements:

1. Gap between ".ncanopy" and ".popupImg": The current gap between these two sections is too small compared to the design. Please follow the design carefully and update your code to increase the gap to match the specified design.
![image](https://github.com/MPDADDY/my_portfolio/assets/55840999/c311efcd-1f94-4a91-b379-ff5f215f1211)
By making this adjustment, your layout will be more visually aligned with the design, creating a cleaner and more professional appearance. Keep up the great work, and I'm confident your attention to detail will enhance your project! 👍🌟🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident, sequi fuga veniam labore
Great job on the mobile version! However, there's a small adjustment needed to match the design requirements:

1. Font size: Currently, the font size is set to 10px, but as per the design, it should be increased. Please follow the design and update the font styles, including line height, font size, etc., to match the design.

By making this adjustment, your mobile version will be more visually aligned with the design, creating a better user experience. Keep up the good work, and I'm sure your project will turn out amazing! 👏📱🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    </ul>
Well done on the progress! I have a few suggestions to align your project with the design:

1. Padding: Currently, the top and bottom padding is set to 8px, but as per the design, it should be 4px. Please update your code to match the design's padding.

2. Gap: You've used margins to create gaps between elements, but they don't match the design. Instead, I recommend using the `flex` property with the `gap` property to achieve consistent spacing as per the design.

By making these adjustments, your project will closely resemble the design and provide a more polished and professional appearance. Keep up the excellent work! 👍🎨🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    <button class="popup-links" type="button">See source</button>
Thank you for your hard work! I noticed a couple of areas that need improvement:

1. Vertical Line: As per the design, there should be a vertical line between the "technologies" section and the buttons. However, in your current code, this vertical line is missing. Please ensure you add the vertical line to match the design.

2. Gap Adjustment: The gap between the "technologies" section and the buttons doesn't match the design. I recommend adjusting the gap to align it with the design requirements.
![Uploading image.png…]()

By addressing these issues, your project will be even closer to the desired design. Keep up the good work! 👍🎨🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +                    <button class="popup-links" type="button">See source</button>
- [ ] 👏 Good job adding buttons to your project! However, I noticed that the button styles don't quite match the design requirements. To improve this, I recommend following the design more closely and updating your code to include all button styles, including active and hover states. 

![Design Example](https://github.com/MPDADDY/my_portfolio/assets/55840999/6779d62d-e384-4796-9941-15718adb16a5)

- [ ] Additionally, the design includes an icon for each button, but I noticed that you haven't added the icons in your code. I recommend adding the proper icons as shown in the design.

Please pay attention to font styles, colors, and padding to ensure they align with the design. By making these adjustments, your buttons will look more visually appealing and consistent with the overall design. Keep up the good work! 👍🎨🚀

2023-07-26 14:34 UTC, shahadat3669 commented on details.js
> +        <!--pop up-->${myArticles}`;
👍 Thank you for adding the popup to your project! However, as per the project requirements, the popup for the mobile version should be responsive from 375px to 768px, and above 768px, the desktop version should be shown. Currently, your popup does not meet this responsive requirement. Please review your code and make the necessary updates to ensure that the popup behaves responsively as specified in the project requirements. Test your changes on different screen sizes to ensure that the popup displays correctly on both mobile and desktop devices.

2023-07-26 16:52 UTC, MPDADDY commented on details.js
> +  },
Thank you for the descriptive explanation.

2023-07-26 18:11 UTC, shahadat3669 requested changes
Hi @MPDADDY, @Obimbo07, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Descriptive PR Title and Description
✅ Button has active and hover styles 👍 



 ## Required Changes ♻️

- [ ] 👍 Thank you for your hard work and effort in updating the code based on the previous review! I appreciate your dedication to learning and improving the project. I understand that there were many changes required to meet the project requirements, and it's completely normal to take things one step at a time. Remember, the requirements are meant to help you learn and grow as a developer, and they are not meant to hold you back. Take your time to understand each requirement and implement them one by one. 🆙 It's a great way to enhance your skills and ensure that the project aligns with the design and functionality expectations. Please go through each comment and update your code. 🙏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 06:54 UTC, addod19 commented
## Hi @MPDADDY and @Obimbo07,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Highlights
- [ ] Great job fixing the comment from the previous review 🚀 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 06:57 UTC, merged